# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: "Upload Cloudformation files"
          command: "aws cloudformation create-stack --stack-name sampleStack- -region ap-northeast-1 --template-body file://sample_stack.yml"
      - run:
          name: "Wait Stack Complete"
          command: "aws cloudformation wait stack-create-complete --stack-name sampleStack"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
